#!/usr/bin/env bash
#Redirection 301
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo sed -i "/server_name _;/ a\\\trewrite ^/redirect_me https://www.youtube.com permanent;" /etc/nginx/sites-available/default
sudo service nginx start
