#!/usr/bin/env bash
# Configuration and Installation haproxy
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy=2.0.\*
echo "\
frontend load_balancer
    bind *:80
    mode http
    default_backend betty
backend betty
    mode http
    balance roundrobin
    server 1149-web-01 35.227.16.88:80 check
    server 1149-web-02 54.144.228.69:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
