#!/usr/bin/env bash
# Configuration and Installation haproxy
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chmod 777 /etc/haproxy/haproxy.cfg
sudo sed -i "$ a frontend load_balancer \n\t bind *:80 \n\t mode http \n\t default_backend betty \n\n backend betty \n\t mode http \n\t balance roundrobin \n\t server 1149-web-01 35.227.16.88:80 check \n\t server 1149-web-02 54.144.228.69:80 check \n" /etc/haproxy/haproxy.cfg
sudo service haproxy restart
