#!/usr/bin/env bash
#Bash script that...
file=/var/run/holbertonscript.pid
trap 'echo Y U no love me?!' 2
trap 'rm $file; exit' 3
trap 'echo I hate the kill command; rm $file; exit' 15
echo $$ > "$file"
while true; do
echo "To infinity and beyond"
sleep 2
done
