#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and:
Hour=0
while [ $Hour -lt 12 ]; do
    echo "Hour: "$Hour
    Minute=1
    while [ $Minute -lt 59 ]; do
	echo $Minute
	let Minute=Minute+1
    done
    let Hour=Hour+1
done
