#!/usr/bin/env bash
# Script that loops from 1 to 10 and:
Hour=0
while (( $Hour <= 12 )); do
    echo "Hour:" $Hour
    Minutes=1
    while (( $Minutes <= 59 )); do
	echo $Minutes
	let Minutes+=1
    done
    let Hour+=1
done
